language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: JHgPyNzG0k+m3Ir4p2Fx4j6BbisbR7dQ6y9iokhFG6EnNq1Fx/hu9OKqDnP7JobJeO1Y7wiA3nFg6INpeF2C8rfOtDWYjap4EQE9WJrStUhyDGbTLH1FRdw7hjTLwWAYzTNEqOHzCZcCOFXly3Y8fyHn3PSDwPnkZj/vvdKg25R+0VbPlWP0MUx/tNkC7saDAl3f841cXPuPLvcr90CDFHv8w4urXOrIjTX8RISdnWTdhKME57dlURPDwhz4jkaZzoHRbdZBOycV8gCQl0/orotZYvYSm0zbEqFW1VEL8ml1eG28HNLFZzEfZ6EY4KoQHcV6+UNtnNLi58mDH/t9Yz6vVOoiwBnX5axTHLW77Ckp0i3UvC1zrq4gLogKxZy4MlVOl6QVgidHicvfKRDgi0z/yUvMWVWptvLHOAANApDQ7v2Laove2aZU0y4daDYyuMWKZzNk5xt50/0tot9I+fuQTHAbH+eT8rP4VZJOudk4zY+Sv86z8wcsgRXG4jUYxghXZRlscjoZMgrCqGtUdAbGgZU7CvFAsnagyxe/sSj1MTu03sinWRXTx6glAABT1vUp4QH04RYz0bLroxCB4pNXUKOgayLCBT5WjlQuzAEvk708x/+UymkpmD4RzLvR3a9sQXJdYFEscm80u1LL/9Gne63HTkIqosOIcvSgffo=
script: mvn clean test
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
