language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: "QgRUi6okdvCVvP31ZNmXuerg53RmgJXDTsGcxnobWEnQ0dxteD6B7iPF42sZtAzkruy1HI6HLwJYEUuK1E/vYEyhKJynMU4y3wbzpVPbSJOatrJl24EOJx1wm09+SQHfu77/6xbhdej2sOzxD061fJPHwRc7p5xOz4RfW3bHu5lsPW+bFle7xZ8k7oU+QR8z/xLWAIjz6w4ju23IImADv2RstnrRlRtv/MijcQzDGvOHea+iHicnqjI34+ce9HHcrWhFMXfhWtEX/a5piaMCgo/e0U2uf5KhrYO4uc7ZVG7Pfvd0bACE0zVRsBAKMAJikg63hf71jwC8BAfAe7aUfqT1fMpgLoxYfLjrsnuCsssFdAhwGrYmXgL+4vxhtESjJ0Hts+vkUgct8ij3yv1QppC8/cCn/IBlx8Vdy6wVXYhU8EGgxkEvDkwjoZudLy7uaeQkfRYnV0GlQ2jmqnuBvUvHraaIElxltV3G4zQBpzbEwjAQ/KTolBkNF5555F9iiOxm2z3zSVrpja0rfENY8Gn4fgI9x8uaDhRfi2Hss8d8V7vZcll/3qzVwJAfN1mir11qjOoLAyr49qV4BkN+6/BihJZqVnRoDauASg5d9t/lwr+ozpx6bXlfO31kuJsyetoLF+BcEcFU+x+Ora5Qj6LKY3MPygsqfy0RIz9Vuhs= SONATYPE_PASSWORD=pass"
script: mvn clean test
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
